Refactor Review Controller & add animation to close button
lauyoo46/FoodPin pull request #19
Opened 2020-12-15 16:05 UTC by lauyoo46

2020-12-16 07:42 UTC, czegreanu requested changes

2020-12-16 07:42 UTC, czegreanu commented on FoodPin/Controller/ReviewViewController.swift
> +    @IBAction func closeButtonPressed(_ sender: UIButton) {
do we need this?

2020-12-16 09:04 UTC, czegreanu approved these changes

2020-12-17 08:46 UTC, a-nistor approved these changes

2020-12-17 08:46 UTC, a-nistor approved these changes

2020-12-17 08:51 UTC, merged