Adds core data support for inserting & deleting restaurants
lauyoo46/FoodPin pull request #22
Opened 2020-12-17 13:51 UTC by lauyoo46

<img width="434" alt="Screenshot 2020-12-17 at 15 49 15" src="https://user-images.githubusercontent.com/38860865/102496150-b5336280-407f-11eb-967b-c6864b5bc724.png">
<img width="434" alt="Screenshot 2020-12-17 at 15 49 46" src="https://user-images.githubusercontent.com/38860865/102496155-b6fd2600-407f-11eb-8aac-a253274264cb.png">
<img width="434" alt="Screenshot 2020-12-17 at 15 49 53" src="https://user-images.githubusercontent.com/38860865/102496157-b8c6e980-407f-11eb-9ab0-8c51995f91c1.png">

2020-12-17 13:57 UTC, a-nistor commented on FoodPin/Controller/ReviewViewController.swift
> -    var restaurant = Restaurant()
it's preferable to keep variables that are not outlets as optional

2020-12-18 07:51 UTC, czegreanu approved these changes

2020-12-18 08:47 UTC, a-nistor requested changes

2020-12-18 08:47 UTC, a-nistor commented on FoodPin/Controller/MapViewController.swift
> +        guard let restaurantLocation = restaurant?.location else {
you can use a single guard with multiple let's separated by commas

2020-12-18 08:47 UTC, a-nistor commented on FoodPin/Controller/RestaurantDetailViewController.swift
> +        headerView.nameLabel.text = restaurantName
if you check in UIKIT, the text property of a UILabel is declared as String?. So you don't need to cast to String before assigning an optional to it.
And for future reference, a guard cast is useful for example when we need to use that variable multiple times, but for single uses we should try using the ternary operator.

2020-12-18 10:58 UTC, a-nistor approved these changes

2020-12-18 11:00 UTC, merged